name: Run automated tests

on: push

jobs:
  coverage:
    name: Check coverage with coverage.py
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: ./.github/actions/setup-environment
      - name: Run unit tests
        run: uv run coverage run
      - name: Report coverage
        run: uv run coverage report --format markdown >> $GITHUB_STEP_SUMMARY
      - name: Generate coverage artifacts
        if: ${{ failure() }}
        run: |
          uv run coverage html --fail-under 0
          uv run coverage xml --fail-under 0
          uv run coverage json --fail-under 0
          uv run coverage lcov --fail-under 0
          uv run coverage annotate
      - name: Upload artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: Coverage reports
          path: |
            coverage.json
            coverage.lcov
            coverage.xml
            htmlcov/
            *.py,cover
