# Copyright 2025 NV Access Limited
#
# This file is part of the NVDA Remote Access Relay Server.
#
# NVDA Remote Access Relay Server is free software: you can redistribute it and/or modify it under the terms
# of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# NVDA Remote Access Relay Server is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero
# General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License along with NVDA Remote Access Relay
# Server. If not, see <https://www.gnu.org/licenses/>.

name: Check types with Pyright

on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main

jobs:
  pyright:
    name: Check types with pyright
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: ./.github/actions/setup-environment
      - name: Run pyright
        run: uv run pyright >> $GITHUB_STEP_SUMMARY
